### ISSUE TITLE
Créer une classe Folder dans le module api

### ISSUE THREAD

**Issue by Hugues-DTANKOUO** [Hugues-DTANKOUO/Fax#2]
Cette classe `Folder` représente un dossier avec des propriétés minimales.
Il est important de bien documenter sa classe et de commenter son code.
Il faut également écrire un test unitaire pour cette classe.

Ne pas oublier d'exécuter la commande
    ```shell
    poetry run check
    ```
avant de pousser ses changements

**Comment by Mahouton** [comment]
Si j'ai bien compris le problème à résoudre, il faut qu'on crée un fichier (par exemple **folder.py**  avec une implémentation minimale de la classe **Folder**) dans le dossier api du projet ?
Ou bien ce n'est pas encore une tâche à gérer

**Comment by Hugues-DTANKOUO** [comment]
Je recommande de créer un dossier `models` dans le dossier `api` avant d'y ajouter comme tu l'as dis, un fichier `folder.py`

**Comment by Mahouton** [comment]
D'accord Ing, c'est noté.

**Comment by Mahouton** [comment]
La classe Folder a été créé avec une implémentation minimale.
Le test unitaire a été réalisé, mais échoue à cause d'un soucis d'importation de la Classe Folder dans le fichier de test
Toutefois Le push a été fait sur la branch [https://github.com/Mahouton/Fax/tree/devops_paul](https://github.com/Mahouton/Fax/tree/devops_paul)
